# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    fitness_steps:
        class: FitnessBundle\Service\StepService
        arguments: ["@httplug.message_factory", "@httplug.client.fitness", "@hwi_oauth.resource_owner.google"]
